[package]
name = "logicrs"
version = "0.1.0"
edition = "2021"
description = "An easy-to-use simulator for logical circuits"
readme = "./README.md"
# repository = "https://github.com/spydr06/logicrs"
license = "MIT"
authors = ["Spydr06 https://github.com/spydr06"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.adw]
package = "libadwaita"
version = "0.1.1"